import { Inter, Source_Code_Pro } from "next/font/google";
import '.././globals.css';
import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs";
import Loader from "@/components/Loader";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import SessionWrapper from "@/components/SessionWrapper";
import CommentModal from "@/components/CommentModal";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <SessionWrapper>
        <html lang='en'>
          <body
            className={`${inter.variable} ${sourceCodePro.variable} antialiased`}
          >
            <ClerkLoading>
              <Loader />
            </ClerkLoading>
            <ClerkLoaded>
              <div className='flex justify-between max-w-8xl mx-auto'>
              <div className=' h-screen sticky top-0'>
                <LeftSidebar />
              </div>

                <div className='w-6xl flex-1'>{children}</div>
                <div className='lg:flex-col p-3 h-screen hidden lg:flex w-[24rem]'>
                  <RightSidebar />
                </div>
              </div>
              
            </ClerkLoaded>
            <CommentModal />
          </body>
        </html>
      </SessionWrapper>
    </ClerkProvider>
  );
}